---
title: Publication-Ready Maps in R
author: Bryce Mecum
---

## Introduction

Making maps entirely using R is one thing but making a map using R that look good enough to go in your next journal manuscript or conference talk is *another* thing.
Historically, this has been pretty hard to do in R and the bad news is that it's not easy or wonderful just yet.
This lesson shows two methods I've found to make a map using R that has a zoomed-out inset and other common features of maps.

## Learning objectives

After completing this lesson the student will have produced publication ready maps using two separate approaches.

## Lesson

The lesson itself is contained in the two R scripts in this directory.
The [first method](./method_one_maps.R) uses the `maps` package.
The [second method](./method_two_gg.R) uses the `ggplot2` package.
Explore each of these scripts and try to get a feel for how they work.
As a challenge, try adapting these scripts for a map you might want to make.

## Summary

Publication-ready maps in R are still a bit challenging but there are at least two general ways of doing them.