---
title: R Review & Assessment
---

- Time slot: 60 minutes
- Learning outcomes:
    - Refresh general R programming skills
    
Concepts:

variables
  assignment
types
  vectors
    character vecs / strings
      
  lists
  vectors vs. lists
    - touch on the fact that vectors are for one type and lists are for multi
    - what does this do? `r c(1, "asdf", 2)`
  data.frames
data import/export (e.g. read.csv)
data manip
  subset
  data.frame[] notation
plotting
modeling
common util functions
  paste (combine things)
  table
  summary
  str
  seq
  nchar
strings vs factors
iteration
  for loops
    - when do we use for loops? when we're doing for each X where X can be year, site, etc.
apply-family


functions? prob skip because this will be taught separately

Other good resources:

- Great, free book: http://r4ds.had.co.nz/
- DataCamp's R intro, https://www.datacamp.com/courses/free-introduction-to-r
Sources:
- Used https://www.rstudio.com/resources/cheatsheets/ to make sure I wasn't missing any basic stuff